import {body} from "express-validator";


export const BlogNameValidator = body('name')
    .trim()
    .notEmpty()
    .withMessage('name is required')
    .isString()
    .isLength({min: 1, max: 15})
    .withMessage('name should 2 - 15 symbols')

export const BlogDescriptionValidator = body('description')
    .trim()
    .notEmpty()
    .withMessage('description is required')
    .isString()
    .isLength({min: 1, max: 500})
    .withMessage('description should 2 - 500 symbols')

export const BlogWebsiteUrlValidator = body('websiteUrl')
    .trim()
    .notEmpty()
    .withMessage('websiteUrl is required')
    .isString()
    .isLength({min: 1, max: 100})
    .withMessage('websiteUrl should 2 - 500 symbols')
    .matches("^https://([a-zA-Z0-9_-]+\.)+[a-zA-Z0-9_-]+(\/[a-zA-Z0-9_-]+)*\/?$")
    .withMessage('not correct')

export const PostTitleValidator = body('title')
    .trim()
    .notEmpty()
    .withMessage('title is required')
    .isString()
    .isLength({min: 1, max: 30})
    .withMessage('title should 2 - 30 symbols')

export const PostShortDescriptionValidator = body('shortDescription')
    .trim()
    .notEmpty()
    .withMessage('shortDescription is required')
    .isString()
    .isLength({min: 1, max: 100})
    .withMessage('shortDescription should 2 - 100 symbols')

export const PostContentValidator = body('content')
    .trim()
    .notEmpty()
    .withMessage('content is required')
    .isString()
    .isLength({min: 1, max: 1000})
    .withMessage('content should 2 - 1000 symbols')

export const PostBlogIdValidator = body('blogId')
    .trim()
    .isString()
    .withMessage('blogId is required')
